name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm test
      - run: npm build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.TOKEN }}
